/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.louistsaitszho.hackernews_retrofit

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
